# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53b1773308d4627ff0273938d219fdbc5689fe9b4b1d3d06cbff3ab7707fbbf3b68ef4fd4fcfe8d173c0a72204dddb807d3fc73dcf7c6512122093bd908f6445

test:
  secret_key_base: 0b3826e64604156bc6ba1826979c8b3ec031ef77038f2e55fc32e4aa1dd09924fcdbb74d44d1a545343da009836b8d6c5942b437eecacee9a92d6f7e2b68503e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
